name: "Running all checks"
on:
  push:
  pull_request:
jobs:
    Run-Linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install
            - name: Run Linting
              run: npm run lint
    Run-Typecheck:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Dependencies
              run: npm install
            - name: Run Typechecking
              run: npm run typecheck
    # Run-Tests:
    # will add later